Fix tags being serialized as stringified map objects
This commit fixes an issue where the `tags` key of pins in the API response would be serialized as the string `"<map object at 0x...>". This issue would cause a `TypeError: pins.objects[i].tags.sort is not a function` on the frontend and prevent the page from loading.